version: 3,
services:
  postgres:
    mem_limit: 512m
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env

  postgres_admin:
    mem_limit: 512m
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - '15432:80'

  mongo:
    image: mongo
    ports:
      - 27017:27017

  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    network_mode: bridge
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  auth:
    mem_limit: 512m
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
      target: development
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev auth && npx prisma migrate dev

  cart:
    mem_limit: 512m
    build:
      context: ./
      dockerfile: ./apps/cart/Dockerfile
      target: development
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev cart && npx prisma migrate dev

  catalog:
    mem_limit: 512m
    build:
      context: ./
      dockerfile: ./apps/catalog/Dockerfile
      target: development
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev catalog && npx prisma migrate dev

  orders:
    mem_limit: 512m
    build:
      context: ./
      dockerfile: ./apps/orders/Dockerfile
      target: development
    env_file:
      - .env
    depends_on:
      - postgres
      - cart
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev orders && npx prisma migrate dev

  gateway:
    mem_limit: 512m
    build:
      context: ./
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev gateway && npx prisma migrate dev
volumes:
  redis:
    driver: local
